[package]
name = "parse"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { workspace = true }

logos = "0.15.0"
typed-index-collections = { workspace = true }
[dev-dependencies]
pretty_assertions = "1.4.1"
assert_matches = "1.5.0"
