[workspace]
members = ["ui", "parse", "eval"]
resolver = "3"

[workspace.dependencies]
typed-index-collections = "3.3.0"
parse = { path = "parse" }
derive_more = { version = "2.0.1", features = ["from", "into"] }
